ming:
  auth:
    clientId: ENC(rQCI1lOpsud4BWlLQMxn9ClLK/b2880F)
    clientSecret: ENC(+2p9S5Cs1L7Z6eyJA8spzGzSSNIzRhoI)
    scope: server

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token