server:
  port: 1004

spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .templates.ftl
    template-loader-path: classpath:/templates/

ming:
  auth:
    clientId: ENC(tEg7vPpjdLj7C9BfMgAtvg==)
    clientSecret: ENC(tEg7vPpjdLj7C9BfMgAtvg==)
    scope: server

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /actuator/health
    - /metrics/**
    - /loggers/**
    - /mobile/token