server:
  port: 1004
ming:
  auth:
    clientId: ENC(tEg7vPpjdLj7C9BfMgAtvg==)
    clientSecret: ENC(tEg7vPpjdLj7C9BfMgAtvg==)
    scope: server

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /actuator/health
    - /metrics/**
    - /loggers/**
    - /mobile/token