spring:
  application:
    name: auth-service
  redis:
    host: 49.232.4.6
    password: m6i1m2a3
    database: 0
    port: 6321
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

ming:
  jwt:
    jwtkey: jwt:token:ming

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token