server:
  port: 1004
ming:
  auth:
    clientId: ENC(H+Ujylg8J3e7QymVchGmDBIf+NiKciFl)
    clientSecret: ENC(H+Ujylg8J3e7QymVchGmDBIf+NiKciFl)
    scope: server
    username: username
    password: password

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /actuator/health
    - /metrics/**
    - /loggers/**
    - /mobile/token