spring:
  application:
    name: auth-service
    profiles:
      include: common-config

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"