spring:
  application:
    profiles:
      include: common-config
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/default-error
zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
      sensitiveHeaders:
#  ratelimit:
#    key-prefix: user-ratelimite
#    enabled: true
#    repository: REDIS
#    behind-proxy: true
#    policies:
#      user-service:
#        limit: 100
#        quota: 100
#        refresh-interval: 3 #3秒内允许300个访问，平均每个请求2秒，并且要求总请求时间小于2400秒