spring:
  redis:
    host: 49.232.4.6
    password: m6i1m2a3
    database: 0
    port: 6321
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/default-error
zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
      sensitiveHeaders: