spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(F+YkgT3pkCtS8/75kJLB/A==)
    password: ENC(F+YkgT3pkCtS8/75kJLB/A==)
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    password: m6i1m2a3
    database: 0
    port: 6321
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/default-error

zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      user:
        - limit: 100
          refresh-interval: 3 #3秒内允许300个访问，平均每个请求2秒，并且要求总请求时间小于2400秒
          type:
            - url