spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    password: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

urls:
  collects:
    - /mobile/**
    - /auth/**
    - /actuator/health
    - /webjars/**
    - /user/code/*
    - /user/api/info
    - /user/api/userTree
    - /user/api/dictType/*