spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    password: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/default-error

zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      user:
        - limit: 100
          refresh-interval: 3 #3秒内允许300个访问，平均每个请求2秒，并且要求总请求时间小于2400秒
          type:
            - url

security:
  validate:
    code: false
  sessions: stateless
  auth:
    server: http://localhost:1004
  oauth2:
    client:
      client-id: ENC(H+Ujylg8J3e7QymVchGmDBIf+NiKciFl)
      client-secret: ENC(H+Ujylg8J3e7QymVchGmDBIf+NiKciFl)
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token #由资源服务器用来解码访问令牌
      service-id: gateway-service
      jwt:
        #key-uri: ${security.auth.server}/oauth/token_key #使用JWT令牌，RSA公开密钥可以用于令牌验证
        key-value: ENC(tEg7vPpjdLj7C9BfMgAtvg==)

urls:
  collects:
    - /mobile/**
    - /auth/**
    - /actuator/health
    - /webjars/**
    - /user/code/*
    - /user/api/info
    - /user/api/userTree
    - /user/api/dictType/*