spring:
  application:
    git:
      generator:
        enabled: false
    group:
      generator:
        character: '-'
        length: 15
        enabled: false
    strategy:
      tracer:
        enabled: true
      logger:
        debug:
          enabled: true
        enabled: true
      monitor:
        enabled: true
      consumer:
        isolation:
          enabled: true
      register:
        isolation:
          enabled: true
      gateway:
        header:
          priority: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    password: ENC(Z3cgiTeEq+Cnl0MGrX7teA==)
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: user-service
          uri: grayLb://user-service
          predicates:
            - Path=/user/**
        - id: user-service-v1
          uri: lb://user-service
          predicates:
            - Path=/details/**
            - Weight=group1, 5
          filters:
            - AddRequestHeader=hello, world
        - id: user-service-v2
          uri: lb://user-service
          predicates:
            - Path=/details/**
            - Weight=group1, 5
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://10.10.35.236:1004/rsa/publicKey'

urls:
  collects:
    - /mobile/**
    - /auth/**
    - /actuator/health
    - /webjars/**
    - /user/code/*
    - /user/api/info
    - /user/api/userTree
    - /user/api/dictType/*