spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(F+YkgT3pkCtS8/75kJLB/A==)
    password: ENC(F+YkgT3pkCtS8/75kJLB/A==)
    url: jdbc:mysql://10.10.35.236:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"